Models/Camiones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camiones
    {
        public int ID_Camion { get; set; }
        public string Matricula { get; set; }
        public string Tipo_Camion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Capacidad { get; set; }
        public double Kilometraje { get; set; }
        public string UrlFoto { get; set; }
        public bool Disponibilidad { get; set; }
    }
}

Controllers/CamionesController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TransportesMVC.Models;

namespace TransportesMVC.Controllers
{
    public class CamionesController : Controller
    {
        // GET: Camiones
        public ActionResult Index()
        {
            //crear una lista del modelo original
            List<Camiones> list_camionoes = new List<Camiones>();

            //lleno la lista con elementos existentes dentor del contexto (BD) utilizando EF y LinQ
            using (TransportesEntities context = new TransportesEntities())//es desechable, solo se ejecuta una vez y desaparece
            {
                //lleno mi lista directamente usando linq
                list_camionoes = (from camion in context.Camiones select camion).ToList();
                //otra forma de usar linq es 
                //list_camionoes = context.Camiones.ToList();
                //otra forma de hacerlo
                /* foreach(Camiones cam in context.Camiones){
                 list_camionoes.Add(cam);
                 }*/
            }
            //ViewBag  (forma parte de razor) se caracteriza por hacer uso de una propiedad arbitraria que sirve para pasar informcion desde el controlador a la vista
            ViewBag.Titulo = "Lista de camiones";
            ViewBag.Subtitulo = "Utilizando ASP.NET MVC";

            //ViewData se caracteriza por hacer uso de un atributo arbitrario y tiene el mismo funcionamiento que el ViewBag
            ViewData["Titulo2"] = "Segundo titulo";

            //TempData se caracterizza por premitir crear variables temporales que existen durante la ejecucion del runtime de asp
            // ademas, los temdata me permite compartir informacion nos solo del controlador a la vista, si no tambien entre otras vistas y otros controladores
            //tempData.Add("Clave","Valor");

            //retorno la vista con los datos del modelo
            return View(list_camionoes);
        }

        //GET:Nuevo_CAmion
        public ActionResult Nuevo_Camion()
        {
            ViewBag.Titulo = "Nuevo Camion";
            //cargo los DDL con las opciones del tipo camion
            cargarDDL();
            return View();
        }
        //POST: Nuevo_Camion
        [HttpPost]
        public ActionResult Nuevo_Camion(Camiones_DTO model, HttpPostedFileBase imagen)
        {
            try
            {
                if (ModelState.IsValid)//verifica si los campos y los tipos de datos corresponden al modelo (DTO)
                {
                    using(TransportesEntities context = new TransportesEntities())//crea una instancia de un unico uso del contexto
                    {
                        var camion = new Camiones();//creo una instancia de un objeto del modelo original (<Proyecto>.Models)
                        //asigno todos los valores del modelo de entrada (DTO) al objeto que sera enviado a la BD
                        camion.Matricula = model.Matricula;
                        camion.Marca = model.Marca;
                        camion.Modelo = model.Modelo;
                        camion.Tipo_Camion = model.Tipo_Camion;
                        camion.Capacidad = model.Capacidad;
                        camion.Kilometraje = model.Kilometraje;
                        camion.Disponibilidad = model.Disponibilidad;

                        //vaido si existe una imagen en la peticion
                        if (imagen != null && imagen.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(imagen.FileName);//recupero el nombre de la imagen que viene de la peticion
                            string pathdir = Server.MapPath("~/Assets/Imagenes/Camiones/");//mapeo la ruta donde guardare mi imagen en el servidor
                            if (!Directory.Exists(pathdir))//si no existe el directorio , lo creo
                            {
                                Directory.CreateDirectory(pathdir);
                            }
                            imagen.SaveAs(pathdir + filename);//guardo la imagen en el servidor
                            camion.UrlFoto = "/Assets/Imagenes/Camiones/"+filename; //guardo la ruta y el nombre del archivo para enviarlo a la bd
                            //impacto sobre la bd usando EF
                            context.Camiones.Add(camion);//agrego un nuevo camion al contexto
                            context.SaveChanges(); //impacto la base de datos enviando las modificaciones sufridas en el cotexto
                            //sweet alert
                            return RedirectToAction("Index");  //finalmente, regreso al listado de este mismo controlador (camiones) si es que todo salio bien
                        }
                        else
                        {
                            //sweet alert
                            cargarDDL();
                            return View(model);
                        }
                    }
                }
                else
                {
                    //sweet alert
                    cargarDDL();
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                //en caso de que ocurra una excepcion, voy a mostrar un mensae cn el error (sweet alert), voy a devolverle a la vista el modelo que causo el conflico(return View(Model)) y vuelvo a cargar el DDL para que esten disponibles esas opciones(cargarDDL())
                //Sweet Alert
                cargarDDL();
                return View(model);
            }
        }

        //GET:Editar_Camion/{id}
        public ActionResult Editar_Camion(int id)
        {
            if(id > 0)//validar que realmente llegue un ID valido
            {
                Camiones_DTO camion = new Camiones_DTO();//creo una instancia del tipo DTO para pasar informcion desde el contexto a la vista con ayuda en EF y linQ
                using (TransportesEntities context = new TransportesEntities())//cro una instancia de un solo uso de mi contexto
                {
                    //busco a aqul elemento que coincida con el ID
                    //bajo metodo
                    //no puedo colocar directamente un tipo de datos (modelo original) en un DTO, por lo que, primero me calgo de recuperarlo y posteriormente asigno sus valores (mapeo)
                    var camion_aux = context.Camiones.Where(x => x.ID_Camion == id).FirstOrDefault();
                    //otra alternativa
                    var camion_aux2 = context.Camiones.FirstOrDefault(x => x.ID_Camion == id);

                    camion.Matricula = camion_aux.Matricula;//mapeo
                    camion.Marca = camion_aux.Marca;
                    camion.Modelo = camion_aux.Modelo;
                    camion.Capacidad = camion_aux.Capacidad;
                    camion.Kilometraje = camion_aux.Kilometraje;
                    camion.Tipo_Camion = camion_aux.Tipo_Camion;
                    camion.Disponibilidad = camion_aux.Disponibilidad;
                    camion.UrlFoto = camion_aux.UrlFoto;
                    camion.ID_Camion = camion_aux.ID_Camion;

                    //bajo una consulta (usando LinQ)
                    //cuando hago una consulta directa, tengo la oportunidad de asignar valores a tipos de datos mas complejos o diferentes, incluso, pudiendo crear nuevos datos a artir de datos existentes (instancias de clases)
                    camion = (from c in context.Camiones where c.ID_Camion == id select new Camiones_DTO()
                    {
                        ID_Camion = c.ID_Camion,
                        Matricula = c.Matricula,
                        Marca = c.Marca,
                        Modelo = c.Modelo,
                        Capacidad = c.Capacidad,
                        Kilometraje = c.Kilometraje,
                        Tipo_Camion = c.Tipo_Camion,
                        Disponibilidad = c.Disponibilidad,
                        UrlFoto = c.UrlFoto
                    }).FirstOrDefault();
                }//cierre el "using(context)"
                if (camion == null) //valido si realmente recuperé los datos de la bd
                {
                    //sweet alert
                    return RedirectToAction("Index");
                }
                //si todo sale bien, envio a la vista con datos a editar
                ViewBag.Titulo = $"Editar camion {camion.ID_Camion}";
                cargarDDL();
                return View(camion);
            }
            else
            {
                //seet alert
                return RedirectToAction("Index");
            }
        }

        //POST: Editar_Camion
        [HttpPost]
        public ActionResult Editar_Camion(Camiones_DTO model, HttpPostedFileBase imagen)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (TransportesEntities context = new TransportesEntities())
                    {
                        var camion = new Camiones();

                        camion.ID_Camion = model.ID_Camion;
                        camion.Matricula = model.Matricula;
                        camion.Marca = model.Marca;
                        camion.Modelo = model.Modelo;
                        camion.Capacidad = model.Capacidad;
                        camion.Tipo_Camion = model.Tipo_Camion;
                        camion.Disponibilidad = model.Disponibilidad;
                        camion.Kilometraje = model.Kilometraje;

                        if (imagen != null && imagen.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(imagen.FileName);

Views/Camiones/Editar_Camion.cshtml
@model DTO.Camiones_DTO
@*no puede recibir otros datos que no venga de dto*@
@*Indicamos a razor que utilizaremos un modelo a especifico*@
<h2>@ViewBag.Titulo</h2>

@*Comenzamos a crear nuestro formulario
    HTML HELPER BegingForm es el HTML Helper que genera el codigo del formulario
    BeginForm("Metodo", "Controlador", Metodo del protocolo, Especificamos al formualrio que enviaremos inforamacion encriptada (imgs))*@
@using (Html.BeginForm("Editar_Camion", "Camiones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-12">
            <div>
                @*Recuperar y encviar la informacin NO EDITABLE EN 2DO PLANO*@
                @*esta informacion no se  muestra en el formulario, p es requisitop para nuetsro modelo *@

                @Html.HiddenFor(model => model.UrlFoto)
                @Html.HiddenFor(model => model.ID_Camion)

                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Matricula)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Matricula, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Matricula, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Capacidad)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Capacidad, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Marca)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Marca, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Matricula, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Modelo)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Modelo, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Kilometraje)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Kilometraje, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Kilometraje, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Disponibilidad)
                @*generamos una etiqueta input*@
                @Html.CheckBoxFor(model => model.Disponibilidad)
            </div>
            @*ddl tipo de camion*@
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Tipo_Camion)
                @*generamos una dropdownlist que se alimenta de la lista que pasamos por el viewbag*@
                @Html.DropDownListFor(model => model.Tipo_Camion, new SelectList(ViewBag.ListaTipos, "Descripcion", "Descripcion"), new { @class = "form-control" })
            </div>
            @*imagne*@
            <div>
                @Html.LabelFor(model => model.UrlFoto)
                <input type="file" name="imagen" id="imagen" />
            </div>
            @*boton de guardar*@
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}

Views/Camiones/Index.cshtml
@*Reupero el viewbag*@
@*para referenciar un metodo, una variable o un elemento de codigo '@'*@
<h1>@ViewBag.Titulo</h1>
<h1>@ViewBag.Subtitulo</h1>

@*CReo una tabla para mostrar mis camiones*@
@*<table class="table table-bordered table-striped table-striped-columns table-responsive">
        <thead>
            <tr>
                <th scope="col">ID_Camion</th>
                <th scope="col">Matricula</th>
                <th scope="col">Tipo_Camion</th>
                <th scope="col">Marca</th>
                <th scope="col">Modelo</th>
                <th scope="col">Capacidad</th>
                <th scope="col">Kilometraje</th>
                <th scope="col">UrlFoto</th>
                <th scope="col">Disponibilidad</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var camion in Model)
            {
                <tr>
                    <td>@camion.ID_Camion</td>
                    <td>@camion.Matricula</td>
                    <td>@camion.Tipo_Camion</td>
                    <td>@camion.Marca</td>
                    <td>@camion.Modelo</td>
                    <td>@camion.Capacidad</td>
                    <td>@camion.Kilometraje</td>
                    <td>@camion.UrlFoto</td>
                    <td>@camion.Disponibilidad</td>
                </tr>
            }
        </tbody>
    </table>*@

<div class="row">
    <div class="col-md-2" style="text-align:right;">
        <a href="~/Camiones/Nuevo_CAmion" class="btn btn-primary">Nuevo Camion</a>
    </div>
</div>
<div class="col-md-12 row text-center">
    @foreach (var camion in Model)
    {
        //Tarjeta de bootstrap
        <div class="col-md-3 col-sm-12">
            <div class="card" style="width: 18rem;">
                <img src="@camion.UrlFoto" class="card-img-top" alt="@camion.UrlFoto">
                <div class="card-body">
                    <h2 class="card-title">Camion no. @camion.ID_Camion</h2>
                    <h5 class="card-title"></h5>
                    <ul>
                        <li class="card-text">@camion.Capacidad</li>
                        <li class="card-text">@camion.Tipo_Camion</li>
                        <li class="card-text">@camion.Marca</li>
                        <li class="card-text">@camion.Modelo</li>
                        <li class="card-text">@camion.Kilometraje</li>
                        <li class="card-text">@camion.Disponibilidad</li>
                    </ul>
                    <a class="btn btn-warning" href="~/Camiones/Editar_Camion/@camion.ID_Camion">Editar</a>
                    <a class="btn btn-danger" href="~/Camiones/Confirmar_Eliminar/@camion.ID_Camion">Eliminar</a>
                </div>
            </div>
        </div>
    }
</div>

Views/Camiones/Nuevo_Camion.cshtml
@model DTO.Camiones_DTO
@*no puede recibir otros datos que no venga de dto*@
@*Indicamos a razor que utilizaremos un modelo a especifico*@
<h2>@ViewBag.Titulo</h2>

@*Comenzamos a crear nuestro formulario
    HTML HELPER BegingForm es el HTML Helper que genera el codigo del formulario
    BeginForm("Metodo", "Controlador", Metodo del protocolo, Especificamos al formualrio que enviaremos inforamacion encriptada (imgs))*@
@using (Html.BeginForm("Nuevo_Camion", "Camiones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-12">
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Matricula)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Matricula, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Matricula, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Capacidad)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Capacidad, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Marca)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Marca, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Matricula, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Modelo)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Modelo, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Kilometraje)
                @*generamos una etiqueta input*@
                @Html.TextBoxFor(model => model.Kilometraje, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para el msg de validacion*@
                @Html.ValidationMessageFor(model => model.Kilometraje, null)
            </div>
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Disponibilidad)
                @*generamos una etiqueta input*@
                @Html.CheckBoxFor(model => model.Disponibilidad)
            </div>
            @*ddl tipo de camion*@
            <div>
                @*Generamos la etiqueta label*@
                @Html.LabelFor(model => model.Tipo_Camion)
                @*generamos una dropdownlist que se alimenta de la lista que pasamos por el viewbag*@
                @Html.DropDownListFor(model => model.Tipo_Camion, new SelectList(ViewBag.ListaTipos, "Descripcion", "Descripcion"), new { @class = "form-control" })
            </div>
            @*imagne*@
            <div>
                @Html.LabelFor(model => model.UrlFoto)
                <input type="file" name="imagen" id="imagen" />
            </div>
            @*boton de guardar*@
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-success" type="submit"/>
            </div>
        </div>
    </div>
}